# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 04 Jun 2018 15:12:56 +0000
#
# {{ ansible_managed }}
*       @ALL    1
*       @dokuwiki%2dcontributors        16
