<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 04 Jun 2018 15:12:56 +0000
 */
 $conf['title'] = '{{dokuwiki_title}}';
 $conf['license'] = '0';
 $conf['useacl'] = 1;
 $conf['savedir'] = '/srv/dokuwiki_data';
 $conf['authtype'] = 'authldap';
 $conf['superuser'] = '@dokuwiki-admins';
 $conf['disableactions'] = 'register';
 $conf['template'] = '{{dokuwiki_template}}';
 $conf['youarehere'] = 1;
 $conf['useheading'] = '1';

 $conf['plugin']['authldap']['server'] = 'ldap://{{dokuwiki_ldap_server}}';
 $conf['plugin']['authldap']['starttls'] = 1;
 $conf['plugin']['authldap']['usertree'] = 'ou=People,dc=ifb,dc=local';
 $conf['plugin']['authldap']['grouptree'] = 'ou=Groups,dc=ifb,dc=local';
 $conf['plugin']['authldap']['userfilter'] = '(&(uid=%{user})(objectClass=posixAccount))';
 $conf['plugin']['authldap']['groupfilter'] = '(&(objectClass=posixGroup)(|(gidNumber=%{gid})(memberUID=%{user})))';
 $conf['plugin']['authldap']['version'] = 3;
 $conf['plugin']['authldap']['modPass'] = 0;

 $conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
